version: '3.4'

services:
  microserviceeducustomer:
    image: ${DOCKER_REGISTRY-}microserviceeducustomer
    ports:
     - 8080:80 
    build:
      context: .
      dockerfile: MicroServiceEduCustomer/Dockerfile
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    ports:
     - 17433:1433
    environment:
        SA_PASSWORD: Your_password123
        ACCEPT_EULA: Y
